services:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog
      name: mailhog
    spec:
      ports:
        - name: "1025"
          port: 1025
          targetPort: 1025
        - name: "8025"
          port: 8025
          targetPort: 8025
      selector:
        io.kompose.service: mailhog
      type: ClusterIP
    status:
      loadBalancer: {}

deployments:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
      labels:
        io.kompose.service: mailhog
      name: mailhog
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mailhog
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
            app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
            kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
            kompose.service.type: clusterip
            kubernetes.io/ingress.class: traefik
          labels:
            io.kompose.service: mailhog
        spec:
          containers:
            image: ${MAILHOG_IMAGE_NAME}
            name: mailhog
            ports:
              - containerPort: 1025
              - containerPort: 8025
            resources: {}
          imagePullSecrets:
            - name: ${PROXY_IMAGE_PULL_SECRET_NAME}
          restartPolicy: Always
          securityContext:
            fsGroup: 1000
    status: {}

ingressRoutes:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: mailhog
    spec:
      entryPoints:
        - web
      routes:
        - kind: Rule
          match: Host(`${MAILHOG_FQDN}`)
          middlewares:
            - name: custom-error-middleware
              namespace: traefik-int
          services:
            - name: mailhog
              port: 8025
