commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - website-ingressroute.yml
  - website_api_middleware.yml
  # - website-certificate.yml
  # - website_middleware.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
  - website_configmap_volumes.yml

configMapGenerator:
  - name: website-keycloak-config
    files:
      - config/keycloak.json
  - name: website-netlifycms-config
    files:
      - config/netlifycms-config.yml
  - name: website-matomo-config
    files:
      - config/analytics.json
