workflow:
  rules:
    # don't run when a tag is pushed
    - if: $CI_COMMIT_TAG
      when: never
    # don't run when a branch is merged on other branch than the main branch
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: never
    - when: always

stages:
  # Build source code
  - build
  # Build docker images and push them to gitlab registy + nexus
  - image
  # Run unit tests
  - test

include:
  - local: 'commons/.gitlab-ci.yml'
  - local: 'api/.gitlab-ci.yml'
  - local: 'website/.gitlab-ci.yml'
