services:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kompose.volume.size: 200Mi
      creationTimestamp: null
      labels:
        io.kompose.service: clamav
      name: clamav
    spec:
      ports:
        - name: "3310"
          port: 3310
          targetPort: 3310
      selector:
        io.kompose.service: clamav
      type: ClusterIP
    status:
      loadBalancer: {}

autoscaling:
  metadata:
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
      kompose.service.type: clusterip
      kubernetes.io/ingress.class: traefik
    enabled: true
    name: clamav
  spec:
    scaleTargetRef:
      kind: Deployment
      name: clamav
      apiVersion: apps/v1
    minReplicas: 2
    maxReplicas: 8
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 300

deployments:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kompose.volume.size: 200Mi
      creationTimestamp: null
      labels:
        io.kompose.service: clamav
      name: clamav
    spec:
      replicas: 3
      selector:
        matchLabels:
          io.kompose.service: clamav
      strategy: {}
      template:
        metadata:
          annotations:
            app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
            app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
            kompose.image-pull-secret: ${PROXY_IMAGE_PULL_SECRET_NAME}
            kompose.volume.size: 200Mi
            kompose.service.type: clusterip
          creationTimestamp: null
          labels:
            io.kompose.service: clamav
        spec:
          containers:
            image: ${ANTIVIRUS_IMAGE_NAME}
            name: clamav
            ports:
              - containerPort: 3310
            resources:
              limits:
                memory: 4Gi
              requests:
                memory: 2Gi
            startupProbe:
              tcpSocket:
                port: 3310
              initialDelaySeconds: 60
              periodSeconds: 30
              failureThreshold: 3
              timeoutSeconds: 1
            livenessProbe:
              tcpSocket:
                port: 3310
              initialDelaySeconds: 300
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
            readinessProbe:
              tcpSocket:
                port: 3310
              initialDelaySeconds: 90
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
          imagePullSecrets:
            - name: ${PROXY_IMAGE_PULL_SECRET_NAME}
          restartPolicy: Always
    status: {}
