website_image_build:
  extends:
    - .preview-image-job
    - .website-base
  needs: ['website_build']

.website_test_script: &website_test_script |
  yarn test

# website_test:
#   image: ${NODE_BASE_IMAGE_NAME}
#   extends:
#     - .test-job
#     - .website-base
#   script:
#     - *website_test_script
#   artifacts:
#     when: always
#     paths:
#       - ${MODULE_PATH}/coverage/lcov.info
#     expire_in: 5 days
#   needs: ['website_build']
