website_testing_image_build:
  extends:
    - .testing-image-job
    - .website-base
  needs: ['website_build']

website_testing_deploy:
  extends:
    - .testing-deploy-job
    - .website-base
  needs: ['website_testing_image_build']
