apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bus-cert
spec:
  dnsNames:
    - "*.${landscape_subdomain}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: clusterissuer-mcm-dev # dev-mcm-issuer
  secretName: bus-tls
