apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: idp-headers-middleware
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
