commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - idp-ingressroute.yml
  - idp-maas-ingressroute.yml
  - idp-headers-middleware.yml
  # - idp-ratelimit-middleware.yml
  - idp-inflightreq-middleware.yml
  # - idp-certificate.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
  - idp_deployment_set_fsgroup.yml
  - idp_deployment_set_realm_config.yml
  - idp_deployment_set_maas_fsgroup.yml
  - idp_deployment_set_maas_realm_config.yml

configMapGenerator:
  - name: mcm-realm-config
    files:
      - realms/all-realm.json
  - name: maas-realm-config
    files:
      - maas-realm.json
