
{{- range .Values.rbac }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .metadata.name }}
  labels:
  {{- with .metadata.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .metadata.name }}
  labels:
  {{- with .metadata.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .metadata.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .metadata.name }}
    namespace: {{ .metadata.namespace }}
{{- end }}
