{{- range .Values.statefulSet }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  {{- with .metadata.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with .metadata.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .metadata.name }}
spec:
  podManagementPolicy: {{ .spec.podManagementPolicy }}
  replicas: {{ .spec.replicas }}
  selector:
    matchLabels:
      {{- with .spec.selector.matchLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if .spec.updateStrategy }}
  updateStrategy:
  {{- with .spec.updateStrategy }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  serviceName: {{ .metadata.name }}
  template:
    metadata:
      annotations:
      {{- with .spec.template.metadata.annotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .spec.template.metadata.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $k, $v := .spec.template.spec.containers.env }}
        - name: {{ $k }}
          value: {{ $v | quote -}}
        {{- end }}
        {{ if (.spec.template.spec.containers.args) }}
        args:
        {{- range $k, $v := .spec.template.spec.containers.args }}
        - {{ $v | quote -}}
        {{- end }}
        {{- end}}
        name: {{ .spec.template.spec.containers.name }}
        image: {{ .spec.template.spec.containers.image }}
        {{ if (.spec.template.spec.containers.command) }}
        command:
        {{- range $k, $v := .spec.template.spec.containers.command }}
        - {{ $v | quote -}}
        {{- end }}
        {{- end }}
        ports:
        {{- with .spec.template.spec.containers.ports }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{ if (.spec.template.spec.containers.volumeMounts) }}
        volumeMounts:
        {{- with .spec.template.spec.containers.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{ if (.spec.template.spec.containers.securityContext) }}
        securityContext:
        {{- with .spec.template.spec.containers.securityContext }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
      {{ if (.spec.template.spec.containers.terminationGracePeriodSeconds) }}
      terminationGracePeriodSeconds: {{.spec.template.spec.terminationGracePeriodSeconds }}
      {{- end }}
      {{ if (.spec.template.spec.containers.securityContext) }}
      securityContext:
      {{- with .spec.template.spec.securityContext }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{ if (.spec.template.spec.imagePullSecrets) }}
      imagePullSecrets:
        {{- with .spec.template.spec.imagePullSecrets }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      {{ if (.spec.template.spec.volumes) }}
      {{- range $k, $v := .spec.template.spec.volumes }}
      volumes:
      - name: {{ $v.name }}
        {{ if ($v.configMap) }}
        configMap:
          name: {{ $v.configMap.name }}
        {{- end}}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
    {{- with .spec.volumeClaimTemplates }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
