include:
  - local: "antivirus/.gitlab-ci/preview.yml"
    rules:
      - if: $CI_COMMIT_BRANCH !~ /rc-.*/ && $CI_PIPELINE_SOURCE != "trigger" && $CI_PIPELINE_SOURCE != "schedule"
  - local: "antivirus/.gitlab-ci/testing.yml"
    rules:
      - if: $CI_COMMIT_BRANCH =~ /rc-.*/ && $CI_PIPELINE_SOURCE != "trigger"

.antivirus-base:
  variables:
    MODULE_NAME: antivirus
    MODULE_PATH: ${MODULE_NAME}
    ANTIVIRUS_IMAGE_NAME: ${NEXUS_DOCKER_REGISTRY_URL}/clamav/clamav:stable
  only:
    changes:
      - "*"
      - "commons/**/*"
      - "antivirus/**/*"
