api_image_build:
  extends:
    - .preview-image-job
    - .api-base
  needs: ['api_build']

.api_test_script: &api_test_script |
  yarn test --reporter mocha-junit-reporter --reporter-options mochaFile=./junit.xml
  yarn coverage

api_test:
  image: ${TEST_IMAGE_NAME}
  extends:
    - .test-job
    - .api-base
  script:
    - *api_test_script
  artifacts:
    when: always
    paths:
      - ${MODULE_PATH}/coverage/lcov.info
    expire_in: 5 days
  needs: ['api_build']
