include:
  - local: 'api/.gitlab-ci/preview.yml'
    rules:
      - if: $CI_COMMIT_BRANCH !~ /rc-.*/ && $CI_PIPELINE_SOURCE != "trigger" && $CI_PIPELINE_SOURCE != "schedule"

.api-base:
  variables:
    MODULE_NAME: api
    MODULE_TYPE: service
    MODULE_PATH: ${MODULE_NAME}
    API_IMAGE_NAME: ${REGISTRY_BASE_NAME}/fabmob-${MODULE_NAME}-${MODULE_TYPE}:${IMAGE_TAG_NAME}
  only:
    changes:
      - '*'
      - 'commons/**/*'
      - 'api/**/*'

api_build:
  extends:
    - .build-job
    - .api-base
  script:
    - |
      yarn install
  cache:
    key: ${MODULE_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - ${MODULE_PATH}/node_modules/
      - ${MODULE_PATH}/yarn.lock
  artifacts:
    paths:
      - ${MODULE_PATH}/node_modules/
      - ${MODULE_PATH}/yarn.lock
    expire_in: 5 days
