version: '3'

services:
  api:
    image: ${API_IMAGE_NAME}
    build:
      context: .
      dockerfile: ./api-dockerfile.yml
      args:
        NODE_IMAGE_NAME: ${BUILD_IMAGE_NAME}
        CI_PROJECT_ID: ${CI_PROJECT_ID}
        PACKAGE_VERSION: ${PACKAGE_VERSION}
